<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Platform email templates — admin catalogue
    |--------------------------------------------------------------------------
    | Metadata for Admin → Email maintenance. Source: Platform Email Status Report.
    */

    'templates' => [

        // ── Guest — fishing tours ──────────────────────────────────────────

        'guest_booking_request' => [
            'name' => 'Booking Request Submitted',
            'category' => 'guest',
            'description' => 'Confirms the guest that their booking request was received and is awaiting guide response.',
            'view' => 'mails.guest.guest_booking_request',
            'log_type' => 'guest_booking_request',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately after checkout',
            'scheduler_command' => null,
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Guest completes booking checkout',
                'Booking status is pending',
                'Queued mail worker processes the job',
            ],
            'pdf_ref' => '#7',
        ],

        'accepted_mail' => [
            'name' => 'Booking Confirmed',
            'category' => 'guest',
            'description' => 'Sent when a guide accepts the pending booking request.',
            'view' => 'mails.guest.accepted_mail',
            'log_type' => 'booking_accept_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately when guide accepts',
            'scheduler_command' => null,
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Guide accepts booking in dashboard',
                'BookingStatusChanged event → status accepted',
                'Skipped in local environment for some flows',
            ],
            'pdf_ref' => '#8',
        ],

        'rejected_mail' => [
            'name' => 'Booking Rejected (Guest)',
            'category' => 'guest',
            'description' => 'Guide declined the request with a reason and at least one alternative date for rebooking.',
            'view' => 'mails.guest.rejected_mail',
            'log_type' => 'booking_reject_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately when guide rejects',
            'scheduler_command' => null,
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Guide submits reject form with reason + alternative dates',
                'Booking status becomes rejected',
                'CEO also receives reject notification',
            ],
            'pdf_ref' => '#9',
        ],

        'guest_tour_reminder' => [
            'name' => 'Upcoming Tour Reminder',
            'category' => 'guest',
            'description' => 'Reminds the guest that their accepted fishing tour is in 48 hours.',
            'view' => 'mails.guest.guest_tour_reminder',
            'log_type' => 'guest_tour_reminder',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'bookings:send-guest-tour-reminders',
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Booking status is accepted',
                'Tour date is 2–3 days from now (48h window)',
                'Duplicate blocked within 24h via email log',
            ],
            'pdf_ref' => '#11',
        ],

        'guest_review' => [
            'name' => 'Review Request',
            'category' => 'guest',
            'description' => 'Asks the guest to leave a review after their tour has taken place.',
            'view' => 'mails.guest.guest_review',
            'log_type' => 'guest_review',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'bookings:send-guest-reviews',
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Booking status is accepted',
                'Tour date was 24–48 hours ago',
                'Booking not yet reviewed (is_reviewed = 0)',
                'Uses booking email for guest-checkout users',
            ],
            'pdf_ref' => '#12',
        ],

        'guest_expired_booking' => [
            'name' => 'Booking Expired',
            'category' => 'guest',
            'description' => 'Notifies the guest that their request expired because the guide did not respond in time.',
            'view' => 'mails.guest.guest_expired_booking',
            'log_type' => 'guest_booking_expired',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'update:booking-status',
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Booking status is pending',
                'expires_at has passed (24h or 48h window)',
                'Booking auto-cancelled by scheduler',
            ],
            'pdf_ref' => '#13',
        ],

        // ── Guide — fishing tours ──────────────────────────────────────────

        'guide_booking_request' => [
            'name' => 'New Booking Request',
            'category' => 'guide',
            'description' => 'Alerts the guide that a guest submitted a new booking request for their tour.',
            'view' => 'mails.guide.guide_booking_request',
            'log_type' => 'guide_booking_request',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately after guest books',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Guest completes booking checkout',
                'Booking status is pending',
                'Queued mail worker processes the job',
            ],
            'pdf_ref' => '#1',
        ],

        'guide_reminder' => [
            'name' => 'Respond Reminder (24h)',
            'category' => 'guide',
            'description' => 'Reminds the guide to respond before the booking request deadline — 24 hours before expiry.',
            'view' => 'mails.guide.guide_reminder',
            'log_type' => 'guide_reminder',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'bookings:send-guide-reminders',
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Booking status is pending',
                'expires_at is within the next 24 hours',
                'Duplicate blocked via email log',
            ],
            'pdf_ref' => '#2',
        ],

        'guide_reminder_12hrs' => [
            'name' => 'Respond Reminder (12h)',
            'category' => 'guide',
            'description' => 'Final reminder for the guide to accept or reject before the request expires.',
            'view' => 'mails.guide.guide_reminder_12hrs',
            'log_type' => 'guide_reminder_12hrs',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'bookings:send-guide-reminders-12hrs',
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Booking status is pending',
                'expires_at is within the next 12 hours',
                'Duplicate blocked via email log',
            ],
            'pdf_ref' => '#3',
        ],

        'guide_accepted_mail' => [
            'name' => 'Booking Accepted (Guest Details)',
            'category' => 'guide',
            'description' => 'Confirms to the guide that they accepted the booking and includes guest contact details.',
            'view' => 'mails.guide.guide_accepted_mail',
            'log_type' => 'guide_booking_accepted',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately when guide accepts',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Guide accepts booking in dashboard',
                'BookingStatusChanged event → status accepted',
            ],
            'pdf_ref' => '#4',
        ],

        'guide_expired_booking' => [
            'name' => 'Booking Expired',
            'category' => 'guide',
            'description' => 'Notifies the guide that a pending request expired without their response.',
            'view' => 'mails.guide.guide_expired_booking',
            'log_type' => 'guide_booking_expired',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'update:booking-status',
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Booking status is pending',
                'expires_at has passed',
                'Booking auto-cancelled by scheduler',
            ],
            'pdf_ref' => '#5',
        ],

        'guide_upcoming_tour' => [
            'name' => 'Upcoming Tour Reminder',
            'category' => 'guide',
            'description' => 'Reminds the guide that an accepted tour is scheduled in 48 hours.',
            'view' => 'mails.guide.guide_upcoming_tour',
            'log_type' => 'guide_reminder_upcoming_tour',
            'status' => 'active',
            'trigger_type' => 'scheduled',
            'schedule' => 'Hourly cron check',
            'scheduler_command' => 'bookings:send-guide-upcoming-tour-reminders',
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Booking status is accepted',
                'Tour date is exactly 48 hours from now',
                'Duplicate blocked via email log',
            ],
            'pdf_ref' => '#6',
        ],

        'guide_review_confirmation' => [
            'name' => 'New Review Received',
            'category' => 'guide',
            'description' => 'Notifies the guide when a guest submits a review for their tour.',
            'view' => 'mails.guide.review_confirmation_email',
            'log_type' => 'guide_review_confirmation',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when guest submits review',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Guest submits review form',
                'Review linked to accepted booking',
            ],
            'pdf_ref' => '#17',
        ],

        'guide_application_approved' => [
            'name' => 'Account Approved',
            'category' => 'guide',
            'description' => 'Welcomes a new guide after admin approves their application.',
            'view' => 'mails.guide.application_approved',
            'log_type' => 'guide_application_approved',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when admin approves guide',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Admin approves guide application in dashboard',
                'Guide account status set to active',
            ],
            'pdf_ref' => '#18',
        ],

        'guide_invoice' => [
            'name' => 'Invoice',
            'category' => 'guide',
            'description' => 'Guide invoice email — automatic sending is disabled; admin sends manually.',
            'view' => 'mails.guide.guide_invoice',
            'log_type' => 'guide_invoice',
            'status' => 'inactive',
            'trigger_type' => 'manual',
            'schedule' => 'Manual only (auto disabled)',
            'scheduler_command' => 'finance:auto-send-guide-invoices',
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Admin sends invoice from finance dashboard',
                'Automatic command exists but is commented out in scheduler',
            ],
            'pdf_ref' => '#19',
        ],

        // ── Contact requests (general, tours, trips, camps) ───────────────

        'customer_contact_mail' => [
            'name' => 'Contact Confirmation (Customer)',
            'category' => 'other',
            'description' => 'Confirmation to the customer after a general contact form — /contact page, guiding/tour, or trip/camp “ask a question” (no date/guests).',
            'view' => 'mails.customercontactmail',
            'log_type' => 'customer_contact_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent on form submit',
            'scheduler_command' => null,
            'recipient' => 'Customer',
            'trigger_conditions' => [
                'General /contact page, guiding tour page, or trip/camp general contact form',
                'Does NOT include trip/camp booking requests (those use vacation booking emails)',
            ],
            'pdf_ref' => null,
        ],

        'contact_mail' => [
            'name' => 'New Contact Request (Admin Notify)',
            'category' => 'admin',
            'description' => 'Admin notify for general contact requests — general, guiding/tours, and trip/camp questions without booking details.',
            'view' => 'mails.contactmail',
            'log_type' => 'contact_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent on form submit',
            'scheduler_command' => null,
            'recipient' => 'Admin',
            'trigger_conditions' => [
                'Triggered by sendcontact for general & tour/product forms',
                'Sent alongside customer confirmation',
            ],
            'pdf_ref' => null,
        ],

        'vacation_booking_customer_mail' => [
            'name' => 'Trip/Camp Booking Confirmation (Guest)',
            'category' => 'other',
            'description' => 'Confirmation to the guest after submitting a trip or camp booking request (date + guests). Same layout as contact confirmation with booking-focused wording.',
            'view' => 'mails.customercontactmail',
            'log_type' => 'vacation_booking_customer_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent on booking form submit',
            'scheduler_command' => null,
            'recipient' => 'Guest',
            'trigger_conditions' => [
                'Trip or camp booking modal with preferred date and number of persons',
                'Creates TripBooking or CampVacationBooking row',
                'Admin also receives Vacation Booking (Admin Notify)',
            ],
            'pdf_ref' => null,
        ],

        'vacation_booking_admin_mail' => [
            'name' => 'Trip/Camp Booking Request (Admin Notify)',
            'category' => 'other',
            'description' => 'Admin notify when a guest submits a trip or camp booking request. Same layout as contact admin mail with booking-focused wording; CTA links to trip/camp booking admin lists.',
            'view' => 'mails.contactmail',
            'log_type' => 'vacation_booking_admin_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent on booking form submit',
            'scheduler_command' => null,
            'recipient' => 'Admin',
            'trigger_conditions' => [
                'Trip or camp booking modal with preferred date and number of persons',
                'Sent alongside guest booking confirmation',
            ],
            'pdf_ref' => null,
        ],

        'guide_admin_new_request' => [
            'name' => 'New Guide Application (Admin Notify)',
            'category' => 'admin',
            'description' => 'Alerts admin that a new guide has submitted an onboarding application.',
            'view' => 'mails.guide.admin_new_request',
            'log_type' => 'guide_admin_new_request',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when guide submits application',
            'scheduler_command' => null,
            'recipient' => 'Admin',
            'trigger_conditions' => [
                'Guide completes onboarding / application form',
                'Sent to guide_onboarding.admin_notification_email recipients',
                'Guide also receives Application Received',
            ],
            'pdf_ref' => null,
        ],

        'ceo_booking_notification' => [
            'name' => 'New Tour Booking (Admin Notify)',
            'category' => 'admin',
            'description' => 'Alerts CEO/admin when a guest submits a new fishing-tour booking request.',
            'view' => 'mails.ceo.request_mail_to_ceo',
            'log_type' => 'ceo_booking_notification',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately after checkout',
            'scheduler_command' => null,
            'recipient' => 'Admin / CEO',
            'trigger_conditions' => [
                'Guest completes fishing-tour checkout',
                'Queued with guest + guide booking request emails',
            ],
            'pdf_ref' => null,
        ],

        'booking_reject_mail_to_ceo' => [
            'name' => 'Booking Rejected (Admin Notify)',
            'category' => 'admin',
            'description' => 'Alerts CEO/admin when a guide rejects a pending booking request.',
            'view' => 'mails.ceo.reject_mail_to_ceo',
            'log_type' => 'booking_reject_mail_to_ceo',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately when guide rejects',
            'scheduler_command' => null,
            'recipient' => 'Admin / CEO',
            'trigger_conditions' => [
                'Guide rejects booking (BookingStatusChanged → rejected)',
                'Guest also receives Booking Rejected email',
            ],
            'pdf_ref' => null,
        ],

        'booking_cancel' => [
            'name' => 'Booking Cancelled (Admin Notify)',
            'category' => 'admin',
            'description' => 'Alerts CEO/admin when a booking is cancelled (storno path).',
            'view' => 'mails.ceo.cancel_mail_to_ceo',
            'log_type' => 'booking_cancel',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when booking is cancelled',
            'scheduler_command' => null,
            'recipient' => 'Admin / CEO',
            'trigger_conditions' => [
                'Cancel/storno flow in profile (ProfileController)',
                'Guide may also receive guide cancelled notify',
            ],
            'pdf_ref' => null,
        ],

        'guide_cancelled_mail' => [
            'name' => 'Booking Cancelled (Guide Notify)',
            'category' => 'guide',
            'description' => 'Notifies the guide that a booking was cancelled (storno). Guest self-cancel UI is disabled; path still exists in backend.',
            'view' => 'mails.guide.guide_cancelled_mail',
            'log_type' => 'storni_guiding_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when booking is cancelled via storno path',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'ProfileController queues StorniGuidingMail on cancel',
                'Guest cancel button is not exposed in normal UI',
            ],
            'pdf_ref' => '#10',
        ],

        'ddos_alert' => [
            'name' => 'DDoS Alert',
            'category' => 'admin',
            'description' => 'Operational alert when rate-limit / bot / threat protection detects an attack.',
            'view' => 'emails.ddos-alert',
            'log_type' => 'ddos_alert',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when DDoSNotificationService fires (with cooldown)',
            'scheduler_command' => null,
            'recipient' => 'Admin',
            'trigger_conditions' => [
                'Suspicious traffic, honeypot, or blocked IP events',
                'Cooldown controlled by ddos.advanced.alert_cooldown_minutes',
            ],
            'pdf_ref' => null,
        ],

        'guide_application_received' => [
            'name' => 'Application Received',
            'category' => 'guide',
            'description' => 'Confirms to a new guide that their application was received and is under review.',
            'view' => 'mails.guide.application_received',
            'log_type' => 'guide_application_received',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when guide submits application',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Guide completes onboarding / application form',
            ],
            'pdf_ref' => null,
        ],

        'guide_application_rejected' => [
            'name' => 'Application Rejected',
            'category' => 'guide',
            'description' => 'Notifies a guide applicant that their application was not approved.',
            'view' => 'mails.guide.application_rejected',
            'log_type' => 'guide_application_rejected',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent when admin rejects guide application',
            'scheduler_command' => null,
            'recipient' => 'Guide',
            'trigger_conditions' => [
                'Admin rejects guide application in dashboard',
                'Optional rejection reason included',
            ],
            'pdf_ref' => null,
        ],

        // ── Account & registration ───────────────────────────────────────

        'registration_verification' => [
            'name' => 'Registration Email Verification',
            'category' => 'account',
            'description' => 'Asks a new user to confirm their email address after signing up.',
            'view' => 'mails.registration-verification',
            'log_type' => 'registration_verification',
            'status' => 'inactive',
            'trigger_type' => 'immediate',
            'schedule' => 'Would send right after registration (currently disabled)',
            'scheduler_command' => null,
            'recipient' => 'User',
            'trigger_conditions' => [
                'User completes registration form',
                'Send is commented out in RegisterController',
                'RegistrationVerification::build() is also empty / disabled',
            ],
            'pdf_ref' => null,
        ],

        'automatic_registration_mail' => [
            'name' => 'Welcome / Account Activation',
            'category' => 'account',
            'description' => 'Welcome email with temporary login credentials when an account is auto-created (e.g. after guest checkout).',
            'view' => 'mails.guest.automatic_guest_registration',
            'log_type' => 'automatic_registration_mail',
            'status' => 'inactive',
            'trigger_type' => 'immediate',
            'schedule' => 'Would send after auto account creation (currently disabled)',
            'scheduler_command' => null,
            'recipient' => 'User',
            'trigger_conditions' => [
                'Guest checkout creates a full user account',
                'Includes temporary access code / password',
                'Send is commented out in Checkout Livewire',
            ],
            'pdf_ref' => null,
        ],

        'customer_newsletter_mail' => [
            'name' => 'Newsletter Subscription Confirmation',
            'category' => 'account',
            'description' => 'Confirms to the subscriber that their email was added to the newsletter list.',
            'view' => 'mails.customernewsletter',
            'log_type' => 'customer_newsletter_mail',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately on newsletter signup',
            'scheduler_command' => null,
            'recipient' => 'Subscriber',
            'trigger_conditions' => [
                'Visitor submits newsletter signup form',
                'Email is not already on the newsletter list',
                'Admin also receives an internal notify (newsletter mail)',
            ],
            'pdf_ref' => null,
        ],

        'newsletter' => [
            'name' => 'Newsletter Subscription (Admin Notify)',
            'category' => 'admin',
            'description' => 'Internal notification when a visitor subscribes to the newsletter.',
            'view' => 'mails.newsletter',
            'log_type' => 'newsletter',
            'status' => 'active',
            'trigger_type' => 'immediate',
            'schedule' => 'Sent immediately on newsletter signup',
            'scheduler_command' => null,
            'recipient' => 'Admin',
            'trigger_conditions' => [
                'Visitor submits newsletter signup form',
                'Email is not already on the newsletter list',
                'Subscriber also receives confirmation (customer_newsletter_mail)',
            ],
            'pdf_ref' => null,
        ],
    ],

    'categories' => [
        'guest' => ['label' => 'Guest', 'icon' => 'fa-user', 'color' => 'success'],
        'guide' => ['label' => 'Guide', 'icon' => 'fa-compass', 'color' => 'primary'],
        'other' => ['label' => 'Trips & Camps', 'icon' => 'fa-map-marker-alt', 'color' => 'info'],
        'account' => ['label' => 'Account', 'icon' => 'fa-user-plus', 'color' => 'dark'],
        'admin' => ['label' => 'Admin', 'icon' => 'fa-bell', 'color' => 'danger'],
    ],

    'trigger_types' => [
        'immediate' => ['label' => 'Immediate', 'icon' => 'fa-bolt', 'color' => 'warning'],
        'scheduled' => ['label' => 'Scheduled', 'icon' => 'fa-clock', 'color' => 'info'],
        'manual' => ['label' => 'Manual', 'icon' => 'fa-hand-paper', 'color' => 'secondary'],
    ],

    'statuses' => [
        'active' => ['label' => 'Active', 'color' => 'success'],
        'inactive' => ['label' => 'Inactive', 'color' => 'secondary'],
    ],
];
