<?php

/*
| Dial codes offered by phone inputs (includes/forms/phone-input and the tour checkout).
| Key: dial code, value: country label.
*/

return [
    '+49' => 'Germany',
    '+1' => 'USA/Canada',
    '+44' => 'UK',
    '+33' => 'France',
    '+39' => 'Italy',
    '+34' => 'Spain',
    '+81' => 'Japan',
    '+86' => 'China',
    '+91' => 'India',
    '+61' => 'Australia',
    '+353' => 'Ireland',
    '+31' => 'Netherlands',
    '+46' => 'Sweden',
    '+47' => 'Norway',
    '+45' => 'Denmark',
    '+358' => 'Finland',
    '+32' => 'Belgium',
    '+41' => 'Switzerland',
    '+43' => 'Austria',
    '+48' => 'Poland',
    '+351' => 'Portugal',
    '+30' => 'Greece',
    '+420' => 'Czech Republic',
    '+36' => 'Hungary',
    '+7' => 'Russia',
    '+380' => 'Ukraine',
    '+90' => 'Turkey',
    '+20' => 'Egypt',
    '+27' => 'South Africa',
    '+55' => 'Brazil',
    '+52' => 'Mexico',
    '+54' => 'Argentina',
    '+56' => 'Chile',
    '+57' => 'Colombia',
    '+51' => 'Peru',
    '+64' => 'New Zealand',
    '+65' => 'Singapore',
    '+60' => 'Malaysia',
    '+66' => 'Thailand',
    '+62' => 'Indonesia',
    '+63' => 'Philippines',
    '+84' => 'Vietnam',
    '+82' => 'South Korea',
    '+972' => 'Israel',
    '+971' => 'UAE',
    '+966' => 'Saudi Arabia',
];
